### ISSUE TITLE
enable 2factor oauth

### ISSUE THREAD

**Issue by shokai** [shokai/github-cmd#1]
error

```
/Users/sho/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/octokit-3.3.1/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/user: 401 - Must specify two-factor authentication OTP code. // See: https://developer.github.com/v3/auth#working-with-two-factor-authentication (Octokit::OneTimePasswordRequired)
        from /Users/sho/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/response.rb:9:in `block in call'
        from /Users/sho/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/response.rb:57:in `on_complete'
        from /Users/sho/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/response.rb:8:in `call'
        from /Users/sho/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/rack_builder.rb:139:in `build_response'
        from /Users/sho/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/connection.rb:377:in `run_request'
        from /Users/sho/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/faraday-0.9.0/lib/faraday/connection.rb:140:in `get'
        from /Users/sho/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sawyer-0.5.5/lib/sawyer/agent.rb:94:in `call'
        from /Users/sho/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/octokit-3.3.1/lib/octokit/client.rb:339:in `request'
        from /Users/sho/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/octokit-3.3.1/lib/octokit/client.rb:135:in `get'
        from /Users/sho/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/octokit-3.3.1/lib/octokit/client/users.rb:34:in `user'
        from /Users/sho/src/ruby/github-cmd/github-issues:36:in `block in <main>'
        from /Users/sho/src/ruby/github-cmd/github-issues:35:in `each'
        from /Users/sho/src/ruby/github-cmd/github-issues:35:in `<main>'
```

**Comment by shokai** [comment]
created oauth client-id and client-secret https://github.com/settings/applications
